version: "3"

services:

  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile-dev
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend/
      - ./static:/app/static
      - ./media:/app/media

    command: >
      sh -c "echo "AFAF" &&
             python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

    environment:
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASS=postgres
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DB_HOST=db